### ISSUE TITLE
Cleanup for installation

### ISSUE THREAD

**Issue by yixuan** [ryanrsun/GBJ#1]
In order to let users install the package using `devtools::install_github("ryanrsun/GBJ")`, the `*.o` and `*.so` files need to be deleted from the `src` directory. Also, since the package is linking to rather than importing from `BH`, the `DESCRIPTION` file should be changed to

```
...
Imports:
    Rcpp (>= 0.12.7),
    stats
LinkingTo: Rcpp, BH
...
```

**Comment by ryanrsun** [comment]
Thank you for the letting me know about this issue! Have made the suggested changes.
